/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package best.practices.groovy

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class BestPracticesGroovyPlugin implements Plugin<Project> {
    void apply(Project project) {
        project.allprojects { p ->
            println p.path
        }
    }
}
